project:
  type: website
  output-dir: docs

website:
  title: "STAT515_Mid-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - redsign1.qmd
      - redsign2.qmd
      - code.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



