project:
  type: website
  output-dir: docs

website:
  title: "Redesign Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - redesign1.qmd
      - redesign2.qmd
      - code.qmd

format:
  html:
    theme: minty
    #mainfont: arial
    fontsize: 1 rem
    #fountcolor: "0013d5"
    #linkcolor: "#ff33f0"
    #monofont: courier new
    css: styles.css
    toc: true



